# Generated by Django 5.0.1 on 2024-03-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0005_alter_user_name_alter_user_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
