# Generated by Django 5.0.1 on 2024-03-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('role_id', models.IntegerField()),
                ('created_at', models.DateField()),
            ],
        ),
    ]
